version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
  
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  
  web-dev:
    build: .
    command: flask --app app run --host 0.0.0.0 --port 5000 --debug
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
    profiles:
      - dev
